set(SANITIZER "none" CACHE STRING "Sanitizer to enable: none, address, thread, undefined")
set_property(CACHE SANITIZER PROPERTY STRINGS none address thread undefined)

if(SANITIZER STREQUAL "address")
    message(STATUS "Enabling AddressSanitizer + UBSan")
    add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
    add_link_options(-fsanitize=address,undefined)
elseif(SANITIZER STREQUAL "thread")
    message(STATUS "Enabling ThreadSanitizer + UBSan")
    add_compile_options(-fsanitize=thread,undefined -fno-omit-frame-pointer)
    add_link_options(-fsanitize=thread,undefined)
elseif(SANITIZER STREQUAL "undefined")
    message(STATUS "Enabling UndefinedBehaviorSanitizer")
    add_compile_options(-fsanitize=undefined -fno-omit-frame-pointer)
    add_link_options(-fsanitize=undefined)
elseif(NOT SANITIZER STREQUAL "none")
    message(FATAL_ERROR "Unknown sanitizer '${SANITIZER}'. Choose: none, address, thread, undefined")
endif()
